Swap println to writeln
tantivy-search/tantivy-cli pull request #55
Opened 2020-10-06 14:05 UTC by erichutchins

PR to address #54. Swaps `println` for `writeln` and wraps the stdout in a `BufWriter`. I found the latter to add a minor performance improvement, although I’m not completely confident in I/O caching issues.

With 1M entries from the wikipedia sample database, I ran the following tests with hyperfine.

**Locked io::stdout**
```
$ hyperfine 'tantivy-cli/target/release/tantivy search -i wikipedia-index -q "the"'
Benchmark #1: tantivy-cli/target/release/tantivy search -i wikipedia-index -q "the"
  Time (mean ± σ):      9.870 s ±  0.083 s    [User: 9.374 s, System: 0.490 s]
  Range (min … max):    9.791 s … 10.072 s    10 runs

$ hyperfine 'tantivy-cli/target/release/tantivy search -i wikipedia-index -q "barack obama"'
Benchmark #1: tantivy-cli/target/release/tantivy search -i wikipedia-index -q "barack obama"
  Time (mean ± σ):     169.1 ms ±   7.8 ms    [User: 145.5 ms, System: 22.9 ms]
  Range (min … max):   163.9 ms … 193.1 ms    16 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

**Wrapping stdout with BufWriter**
```
$ hyperfine 'tantivy-cli/target/release/tantivy search -i wikipedia-index -q "the"'
Benchmark #1: tantivy-cli/target/release/tantivy search -i wikipedia-index -q "the"
  Time (mean ± σ):      9.137 s ±  0.035 s    [User: 8.954 s, System: 0.175 s]
  Range (min … max):    9.091 s …  9.193 s    10 runs

$ hyperfine 'tantivy-cli/target/release/tantivy search -i wikipedia-index -q "barack obama"'
Benchmark #1: tantivy-cli/target/release/tantivy search -i wikipedia-index -q "barack obama"
  Time (mean ± σ):     163.4 ms ±   0.5 ms    [User: 142.2 ms, System: 21.1 ms]
  Range (min … max):   162.5 ms … 164.6 ms    18 runs
```

2020-10-06 14:51 UTC, fulmicoton commented on src/commands/search.rs
>          }
Please flush handle. `Drop` does flush as well but it does not emit any error if there is an error.

2020-10-06 14:51 UTC, fulmicoton requested changes
I added one comment. Please flush the BufWriter.

2020-10-06 14:52 UTC, fulmicoton commented
Thanks for taking the time to bench this!

2020-10-07 00:44 UTC, merged

2020-10-07 00:49 UTC, fulmicoton commented
I added the flush and merged. (you are still the author of your commits)

2020-10-07 04:07 UTC, erichutchins commented
Thank you @fulmicoton!